name: Build and push

on:
  release:
    types: [published]

env:
  PKG_DEV_BASE_URL: europe-central2-docker.pkg.dev
  DOCKER_IMAGE: europe-central2-docker.pkg.dev/warsawlo/po8klasie

jobs:
  build-push:
    timeout-minutes: 30
    runs-on: ubuntu-latest

    steps:
    # https://github.com/docker/build-push-action/blob/master/docs/advanced/tags-labels.md
    - name: Docker meta
      id: meta
      uses: crazy-max/ghaction-docker-meta@v2
      with:
        images: ${{ env.DOCKER_IMAGE }}
        tags: |
          type=ref,event=tag
          type=sha
        flavor: |
          latest=true

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - id: auth
      name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v0
      with:
        token_format: access_token
        workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
        service_account: ${{ secrets.GCP_DEPLOYMENT_SERVICE_ACCOUNT }}

    - name: Login to Google Artifacts Registry
      uses: docker/login-action@v1
      with:
        registry: ${{ env.PKG_DEV_BASE_URL }}
        username: oauth2accesstoken
        password: ${{ steps.auth.outputs.access_token }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        push: true
        cache-from: type=registry,ref=${{ env.DOCKER_IMAGE }}:cache-master
